### PR TITLE
Founded Rainbow Cycle for g712lw

### PR DESCRIPTION
**Pull request by mkikets99**
Some addition to this lib.

### CODE REVIEW

**Comment by mkikets99** [comment]
This is testet on g712lw
Needs testings on other machines...

**Comment by JoshDreamland** [comment]
Wow, a third one? I swear they come up with a different message for it for each laptop. There's another in #26, if you're curious.

It would be helpful if we could associate these with hardware versions...

**Comment by anishkumar127** [comment]
@mkikets99  u r awesome dude its working <3

**Comment by mkikets99** [comment]
@wroberts  Oh. so this is working on others?
Or I missed something?

**Pull request merged**
